let dares = [
    "{player} nennt seinen besten Anmachspruch und alle, denen er gefällt trinken. Wenn niemand trinkt, trinkt er selbst",
        "{player} sucht sich einen Saufbuddy aus. Immer wenn einer von beiden trinkt, müssen beide trinken! (6 Runden)",
        "Die dümmste Person trinkt 2 Schlücke",
        "Alle trinken so viele Schlücke, wie Personen anwesend sind, mit denen sie schlafen würden. Nicht Lügen!",
        "Die beiden Freunde, die sich am längsten kennen, trinken zusammen.",
        "Alle Fußballfans trinken 2 Schlücke.",
        "Trinkt 2 Schlücke, wenn ihr Pleite seid.",
        "{player} darf die nächsten 5 Runden nur noch Sätze benutzen, in denen 'nicht' vorkommt.",
        "{player} muss 1 Schluck trinken.",
        "Alle Nintendo-Fans trinken.",
        "{player} erzählt seine peinlichste GEschichte. Wenn sie langweilig ist, trinkt er/sie 3 Schlücke. Erzählt er/sie nicht, wird leer getrunken.",
        "Alle, die gerade Bier trinken, müssen 3 Schlücke trinken",
        "Alle, die heute zu spät kamen, müssen ihr Glas exen.",
        "Die nächste Person, die aufs Handy schaut, trinkt 5 Schlücke.",
        "{player} darf so viele Schlücke verteilen, wie er/sie selbst trinkt",
        "Alle, deren Schuhgröße über 46 ist, trinken 3 Schlücke.",
        "Die Person, die heute als letztes aufgestanden ist, verteilt 3 Schlücke.",
        "Verteilt 4 Schlücke, wenn ihr ein Kondom dabei habt. Safety first!",
        "Der letzte, der 'Bitch' ruft, muss 5 Schlücke trinken.",
        "Alle, die kein Schnaps mögen, trinken 2 Schlücke.",
        "{player} darf einen Schluck verteilen.",
        "{player} rennt mit seinem rechten Nebensitzer einmal ums Haus. der Schnellere verteilt 10 Schlücke.",
        "Die intelligenteste Person unter euch verteilt 3 Schlücke.",
        "Alle stimmen ab wer 4 Schlücke nimmt.",
        "Alle Raucher trinken 5 Schlücke.",
        "Alle Hauptschüler trinken 2 Schlücke",
        "{player} muss 3 Schlücke trinken.",
        "Der Besitzer des Handys muss 3 Schlücke trinken.",
        "Diejenigen, die heute gar nicht kommen wollten, trinken 4 Schlücke.",
        "Alle Raucher trinken die Anzahl an Schlücken, die sie heute schon geraucht haben.",
        "{player} verteilt so viele Schlücke, wie Geburtstage von Leuten aus der Runde er/sie kennt.",
        "Die dümmste Person verteilt 4 Schlücke.",
        "Alle Tätowierten trinken.",
        "Alle braunhaarigen trinken.",
        "Alle Realschüler trinken 2 Schlücke.",
        "Die nächste Person, die auf Toilette geht, trinkt 4 Schlücke.",
        "Alle, deren Schuhgröße zwischen 40 und 43 ist, trinken 3 Schlücke.",
        "Die Person mit dem leersten Getränk verteilt 3 Schlücke.",
        "Alle, die kein Bier mögen, trinken 2 Schlücke.",
        "Der/Die Sportlichste trinkt 2 Schlücke.",
        "Alle, die in einer Beziehung sind, trinken 2 Schlücke.",
        "{player} redet die nächsten 8 Runden nur noch mit der Person, die er/sie am coolsten findet.",
        "{player} entscheidet, mit welcher anwesenden Person er/sie am liebsten Sex hätte. Die Person muss 2 Schlücke trinken.",
        "Der mit dem meisten hier vorhandenen Bargeld trinkt 3 Schlücke.",
        "{player} verteilt so viele Schlücke, wie er Münzen dabei hat.",
        "Die Person, die als nächstes lacht, trinkt 2 Schlücke.",
        "{player} darf das nächste Lied entscheiden. Wem es nicht gefällt trinkt einen Schluck.",
        "Alle, die schonmal andere von einer Party abgeholt haben, verteilen 2 Schlücke.",
        "Alle schwarzhaarigen trinken",
        "Alle Frauen trinken 2 Schlücke.",
        "{player} redet die nächsten 4 Runden nur noch mit der Person die er/sie am dümmsten findet.",
        "Verteilt 10 Schlücke, wenn ihr euren Ellbogen lecken könnt.",
        "Alle Männer trinken 2 Schlücke.",
        "Alle, die eine Ausbildung machen, trinken 3 Schlücke.",
        "Trinkt 2 Schlücke, wenn ihr unter der Dusche singt und euch dabei wie ein Superstar fühlt.",
        "Jeder mit einem Haustier trinkt 1 Schluck.",
        "Alle, die gerne einen Partner hätten, trinken 2 Schlücke.",
        "Xbox-Fans trinken.",
        "Alle, deren Beziehungsstatus schwierig ist, trinken. Ihr Armen!",
        "Der/Die Größte trinkt.",
        "Die Frauen trinken ihre Körbchengröße in Schlücken. (A=1,B=2,D=4,...)",
        "{player} darf die nächsten 5 Runden nicht lachen.",
        "{player} verteilt so viele Schlücke, wie er Geldscheine dabei hat.",
        "Alle die ein F im Vornamen haben trinken leer.",
        "Wenn es nach Mitternacht ist, trinken alle.",
        "Alle, die in der letzten halben Stunde geraucht haben, trinken 3 Schlücke.",
        "Alle, die ein J im Vornamen haben trinken 4 Schlücke.",
        "Die Person, die zuerst den Bpden berührt, trinkt 2 Schlücke.",
        "Trinkt 3 Schlücke, wenn euer Auto mehr als 10.000€ wert ist.",
        "Alle Vodka-Trinker nehmen einen Schluck.",
        "Die Person, die zuerst ihr Oberteil ausgezogen hat, verteilt 10 Schlücke.",
        "Alle, die gerade Bier trinken, müssen 3 Schlücke trinken.",
        "Alle, die kein Bier mögen, trinken 2 Schlücke.",
        "{player} darf 4 Schlücke verteilen.",
        "{player} darf die nächsten 5 Runden nur noch Sätze benutzen, in denen Schimpfwörter vorkommen.",
        "{player} muss 3 Schlücke trinken.",
        "Alle Gymnasiasten trinken 2 Schlücke.",
        "Stoßt gemeinsam an!",
        "Ihr dürft die nächsten 7 runden keine Namen mehr nennen. Für jede Namensnennung 2 Schlücke.",
        "{player} zeigt seine Dance-Moves oder trinkt leer.",
        "{player} darf 2 Schlücke verteilen",
        "Die Bitchigste Person trinkt 2 Schlücke",
        "Alle die letzte Runde trinken mussten, trinken nochmal so viel.",
        "Alle singen zusammen ein Lied, welches {player} entscheidet. Wer nicht mitsingt muss 3 Schlücke trinken.",
        "Ab jetzt wird für jedes Schimpfwort getrunken.",
        "Jeder der während dem Spiel schon gefurzt hat, trinkt 2 Schlücke pro Furz.",
        "Die schönste Person unter euch verteilt 4 Schlücke.",
        "Die Person, die am meisten verträgt, trinkt 5 Schlücke.",
        "Alle, die gerne single sind, verteilen 3 Schlücke.",
        "{player} darf 3 Schlücke verteilen.",
        "{player} macht eine rolle oder trinkt 2 Schlücke.",
        "Jeder, der eine Glatze hat, verteilt 2 Schlücke.",
        "Alle, die heute zu spät kamen, müssen ihr Glas exen.",
        "Verteilt so viele Schlücke wie ihr Kleidungsstücke auszieht.",
        "{player} muss die nächsten 3 Runden Angela Merkel immitieren.",
        "Macht euch einen Shot und trinkt gemeinsam",
        "'The floor is lava!' Der Verlierer trinkt 3 Schlücke.",
        "Alle Roothaarigen trinken.",
        "{player} trinkt einen Schluck für jeden, der Mitspielt.",
        "{player}",
        "Alle Frauen exen!",
        "Alle Singles trinken 2 Schlücke.",
        "Jeder, der vergeben ist, trinkt 1 Schluck.",
        "Diejenigen, die gern klugscheißern, trinken 5 Schlücke.",
        "Die Person mit dem leersten Getränkt entscheidet, wer leer trinken muss (und trinkt selbst leer)",
        "Alle Tennisspieler trinken 3 Schlücke.",
        "Der DJ trinkt 2 Schlücke.",
        "{player} zeigt eine Sex-Nachricht auf Whatsapp. Wenn er keine hat trinkt er 4 Schlücke.",
        "{player} sucht sich ein Wort aus, das man die nächsten 4 Runden nicht nennen darf.",
        "Alle Männer trinken 2 Schlücke.",
        "Jeder der rülpst, verteilt 2 Schlücke.",
        "Alle Bierliebhaber trinken leer.",
        "Alle mit Hemd/Bluse machen einen Knopf auf und trinken einen Schluck.",
        "Der DJ verteilt 2 Schlücke.",
        "Jungs trinken so viel wie hübsche Mädchen mitspielen",
        "{player} macht mit seinem/ihrem linken Nebensitzer Armdrücken. Der Verlierer trinkt leer :o",
        "{player} trinkt die nächsten 5 Runden nur Wasser.",
        "{player} muss die nächsten 4 Runden in Reimen sprechen.",
        "Alle Volljährigen trinken 1 Schluck.",
        "{player} trinkt 2 Schlücke wenn er/sie nach 11 Uhr aufgestanden ist.",
        "Alle, die noch zur Schule gehen, trinken einen Schluck.",
        "Die Person mit den coolsten Haaren verteilt 1 Schluck.",
        "{player} darf 2 Schlücke wenn falls er/sie ein Instrument kann.",
        "{player} muss die nächsten 3 Runden auf einem Bein stehen.",
        "Alle iPhone-besitzer trinken 1 Schluck.",
        "Die Person mit dem vollsten Glas darf etwas in das leerste Glas am Tisch kippen.",
        "{player} trinkt 3 Schlücke wenn er/sie schonmal nudes bekommen oder verschickt hat.",
        "Jeder, dessen Eltern getrennt leben darf 1 Schluck verteilen.",
        "Alle Brillenträger trinken 1 Schluck.",
        "{player} muss sich 6 Runden auf seinen/ihren rechten Nebensitzer setzen",
        "Jeder ohne Allergien trinkt 1 Schluck.",
        "Alle, die schonmal Fallschirmspringen waren, trinken 3 Schlücke.",
        "Alle, die schonmal Bungeejumpen waren verteilen 2 Schlücke.",
        "{player} verteilt so viel wie letzte Runde Schlücke getrunken wurden.",
        "Die Person mit dem langsamsten Auto verteilt 4 Schlücke. Alle Ohne Auto trinken 1",
        "{player} zieht sein Oberteil aus oder trinkt leer. Ist es schonweg verteilt er/sie 6 Schlücke.",
        "{player} trinkt die nächsten 2 Runden für seinen Nebensitzer",
        "Die Person, die am höchsten hüpfen kann, darf 4 Schlücke verteilen.",
        "Die Person mit den längsten Haaren trinkt 2 Schlücke.",
        "Alle trinken so lange, bis die erste Person absetzt.",
        "jeder darf so viele Schlücke verteilen wie er/sie Haustiere hat.",
        "Jeder mit Abitur darf einen Schluck verteilen.",
        "Alle Blondinen trinken",
        "Alle, die kein Seepferdchen haben trinken, 1 Schluck."
]